# Generated by Django 5.1.1 on 2024-11-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dietary_preferences',
        ),
    ]
