# Generated by Django 5.1.1 on 2024-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_profile_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='restaurant_name',
            field=models.CharField(max_length=255),
        ),
    ]
