# Generated by Django 5.1.1 on 2024-11-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_profile_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dietary_preferences',
        ),
    ]
