# Generated by Django 5.1.1 on 2024-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_profile_dietary_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
