# Generated by Django 5.1.1 on 2024-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
