# Generated by Django 5.1.1 on 2024-11-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_rename_address_link_profile_address_link_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='times_ordered',
            new_name='order_count',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='restaurant',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
