# Generated by Django 5.1.1 on 2024-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_profile_indoor_tables_profile_outdoor_tables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='WiFi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='WiFi',
            field=models.BooleanField(default=False),
        ),
    ]
