# Generated by Django 5.1.1 on 2024-12-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_special_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='menu_link',
            new_name='site',
        ),
    ]
