# Generated by Django 5.1.1 on 2024-12-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_restaurantcategory_restaurantschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.profile'),
        ),
    ]
