# Generated by Django 5.1.1 on 2024-12-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_restaurantcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.profile'),
        ),
    ]
