# Generated by Django 5.1.1 on 2024-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_restaurantcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
