# Generated by Django 5.1.1 on 2024-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_menuitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_deals',
            name='deal_image',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
