# Generated by Django 5.1.1 on 2024-12-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_remove_profile_indoor_tables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_deals',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='special_deals',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='special_deals',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
