# Generated by Django 5.1.1 on 2024-12-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_restaurant',
            field=models.BooleanField(default=True),
        ),
    ]
