# Generated by Django 5.1.1 on 2024-12-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_profile_is_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
