# Generated by Django 5.1.1 on 2024-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0028_alter_profile_is_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcategory',
            name='category_name',
            field=models.CharField(choices=[('Italian', 'italian'), ('Chinese', 'chinese'), ('Mexican', 'mexican'), ('Indian', 'indian'), ('Japanese', 'japanese'), ('Mediterranean', 'mediterranean'), ('French', 'french'), ('American', 'american'), ('Thai', 'thai'), ('Spanish', 'spanish')], max_length=255),
        ),
    ]
