# Generated by Django 5.1.3 on 2024-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_alter_restaurantcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
