# Generated by Django 5.1.1 on 2024-12-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_remove_review_profile_comment_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
