# Generated by Django 5.1.3 on 2024-12-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0036_delete_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
