# Generated by Django 5.1.1 on 2024-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0041_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_deal',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='special_deals',
            field=models.ManyToManyField(blank=True, to='restaurants.special_deals'),
        ),
    ]
