# Generated by Django 5.1.1 on 2024-12-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0042_remove_order_menu_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_deals',
        ),
        migrations.CreateModel(
            name='MenuItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.order')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDealQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.order')),
                ('special_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.special_deals')),
            ],
        ),
    ]
