# Generated by Django 5.1.3 on 2024-12-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0045_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='num_guests',
        ),
    ]
