# Generated by Django 5.1.1 on 2024-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0047_deliverypartner_delivery_order_delivery_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('takeout', 'Takeout'), ('delivery', 'Delivery')], default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
