# Generated by Django 5.1.1 on 2024-12-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0048_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('takeout', 'Takeout'), ('delivery', 'Delivery')], default='None', max_length=50),
        ),
    ]
