# Generated by Django 5.1.1 on 2024-12-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0049_alter_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='contact_number',
        ),
        migrations.CreateModel(
            name='RestaurantDeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.deliverypartner')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.profile')),
            ],
            options={
                'unique_together': {('restaurant', 'delivery_partner')},
            },
        ),
    ]
