# Generated by Django 5.1.1 on 2024-12-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0051_reservation_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='profile',
            new_name='restaurant',
        ),
    ]
