# Generated by Django 5.1.1 on 2024-12-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0052_rename_profile_table_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='restaurant',
            new_name='profile',
        ),
    ]
