# Generated by Django 5.1.1 on 2025-01-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0054_alter_reservation_restaurant'),
        ('user', '0004_profile_is_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('menu_items', models.ManyToManyField(blank=True, to='restaurants.menuitem')),
                ('restaurant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='restaurants.profile')),
                ('special_deals', models.ManyToManyField(blank=True, to='restaurants.special_deals')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='user.profile')),
            ],
        ),
    ]
